In [5]:
import numpy as np

In [3]:
import pandas as pd

In [1]:
grades = {"Ilker":100, "Irem":90, "Ceren":80}

In [4]:
pd.Series(grades)

Ilker    100
Irem      90
Ceren     80
dtype: int64

In [6]:
names = ["Ilker", "Irem", "Ceren"]

In [7]:
grades = [100, 90, 80]

In [8]:
pd.Series(names)

0    Ilker
1     Irem
2    Ceren
dtype: object

In [9]:
pd.Series(names, grades)

100    Ilker
90      Irem
80     Ceren
dtype: object

In [10]:
pd.Series(index=names, data=grades)

Ilker    100
Irem      90
Ceren     80
dtype: int64

In [11]:
numpy_array = np.array([50, 40, 30, 20])

In [13]:
pd.Series(numpy_array)

0    50
1    40
2    30
3    20
dtype: int64

In [15]:
contest_result = pd.Series(data=[10, 5, 100], index=["Atıl","Ilker", "ırem"])

In [16]:
contest_result_2 = pd.Series(data=[20, 50, 10], index=["Atıl","Ilker", "ırem"])

In [17]:
contest_result["Atıl"]

np.int64(10)

In [18]:
final_result = contest_result + contest_result_2

In [20]:
final_result

Atıl      30
Ilker     55
ırem     110
dtype: int64

In [24]:
different_series = pd.Series([20, 30,
                              40, 50],["a","b","c","d"])

In [22]:
different_series

a    20
b    30
c    40
d    50
dtype: int64

In [25]:
different_series_2 = pd.Series([10, 5,
                              1, 3],["a","c","f","g"])

In [26]:
different_series

a    20
b    30
c    40
d    50
dtype: int64

In [27]:
different_series_2

a    10
c     5
f     1
g     3
dtype: int64

In [29]:
different_series + different_series_2

a    30.0
b     NaN
c    45.0
d     NaN
f     NaN
g     NaN
dtype: float64

In [30]:
data = np.random.randn(4, 3)

In [31]:
data

array([[ 0.1547541 , -0.44130488,  0.22712511],
       [-0.53600539, -0.01837015, -0.28492556],
       [-0.63886867,  0.95329174, -0.43353513],
       [ 0.26675358,  0.23877865, -0.06910332]])

In [32]:
data_frame = pd.DataFrame(data)

In [33]:
data_frame

          0         1         2
0  0.154754 -0.441305  0.227125
1 -0.536005 -0.018370 -0.284926
2 -0.638869  0.953292 -0.433535
3  0.266754  0.238779 -0.069103

In [34]:
type(data_frame)

pandas.core.frame.DataFrame

In [35]:
data_frame[0]

0    0.154754
1   -0.536005
2   -0.638869
3    0.266754
Name: 0, dtype: float64

In [36]:
new_df = pd.DataFrame(data, index = ["Atıl", "Ilker", "Ceren", "Irem"], columns = ["Salary","Age","Seniority"])

In [37]:
new_df

         Salary       Age  Seniority
Atıl   0.154754 -0.441305   0.227125
Ilker -0.536005 -0.018370  -0.284926
Ceren -0.638869  0.953292  -0.433535
Irem   0.266754  0.238779  -0.069103

In [38]:
new_df["Age"]

Atıl    -0.441305
Ilker   -0.018370
Ceren    0.953292
Irem     0.238779
Name: Age, dtype: float64

In [39]:
new_df[["Age", "Salary"]]

            Age    Salary
Atıl  -0.441305  0.154754
Ilker -0.018370 -0.536005
Ceren  0.953292 -0.638869
Irem   0.238779  0.266754

In [40]:
new_df.loc["Ilker"]

Salary      -0.536005
Age         -0.018370
Seniority   -0.284926
Name: Ilker, dtype: float64

In [41]:
new_df.iloc[0]

Salary       0.154754
Age         -0.441305
Seniority    0.227125
Name: Atıl, dtype: float64

In [42]:
new_df.iloc[:,0]

Atıl     0.154754
Ilker   -0.536005
Ceren   -0.638869
Irem     0.266754
Name: Salary, dtype: float64

In [43]:
new_df["Extra"] = 10

In [45]:
new_df

         Salary       Age  Seniority  Extra
Atıl   0.154754 -0.441305   0.227125     10
Ilker -0.536005 -0.018370  -0.284926     10
Ceren -0.638869  0.953292  -0.433535     10
Irem   0.266754  0.238779  -0.069103     10

In [48]:
new_df.drop("Extra", axis=1)

         Salary       Age  Seniority
Atıl   0.154754 -0.441305   0.227125
Ilker -0.536005 -0.018370  -0.284926
Ceren -0.638869  0.953292  -0.433535
Irem   0.266754  0.238779  -0.069103

In [49]:
new_df

         Salary       Age  Seniority  Extra
Atıl   0.154754 -0.441305   0.227125     10
Ilker -0.536005 -0.018370  -0.284926     10
Ceren -0.638869  0.953292  -0.433535     10
Irem   0.266754  0.238779  -0.069103     10

In [51]:
new_df.drop("Extra", axis=1, inplace=True)

In [53]:
new_df

         Salary       Age  Seniority
Atıl   0.154754 -0.441305   0.227125
Ilker -0.536005 -0.018370  -0.284926
Ceren -0.638869  0.953292  -0.433535
Irem   0.266754  0.238779  -0.069103

In [54]:
new_df["Mehmet"] = 10

In [55]:
new_df

         Salary       Age  Seniority  Mehmet
Atıl   0.154754 -0.441305   0.227125      10
Ilker -0.536005 -0.018370  -0.284926      10
Ceren -0.638869  0.953292  -0.433535      10
Irem   0.266754  0.238779  -0.069103      10

In [56]:
new_df.drop("Mehmet", axis=1, inplace=True)

In [57]:
new_df

         Salary       Age  Seniority
Atıl   0.154754 -0.441305   0.227125
Ilker -0.536005 -0.018370  -0.284926
Ceren -0.638869  0.953292  -0.433535
Irem   0.266754  0.238779  -0.069103

In [58]:
new_df.loc["Ilker","Age"]

np.float64(-0.018370148883042343)

In [59]:
new_df.loc["Ilker","Age"] = 50

In [60]:
new_df

         Salary        Age  Seniority
Atıl   0.154754  -0.441305   0.227125
Ilker -0.536005  50.000000  -0.284926
Ceren -0.638869   0.953292  -0.433535
Irem   0.266754   0.238779  -0.069103

In [61]:
new_df > 0

       Salary    Age  Seniority
Atıl     True  False       True
Ilker   False   True      False
Ceren   False   True      False
Irem     True   True      False

In [62]:
boolean_frame = new_df > 0

In [63]:
new_df[boolean_frame]

         Salary        Age  Seniority
Atıl   0.154754        NaN   0.227125
Ilker       NaN  50.000000        NaN
Ceren       NaN   0.953292        NaN
Irem   0.266754   0.238779        NaN

In [64]:
new_df[new_df["Salary"]>0.5]

Empty DataFrame
Columns: [Salary, Age, Seniority]
Index: []

In [65]:
new_df.loc["Ilker","Salary"] = 50

In [66]:
new_df[new_df["Salary"]>0.5]

       Salary   Age  Seniority
Ilker    50.0  50.0  -0.284926

In [67]:
new_df

          Salary        Age  Seniority
Atıl    0.154754  -0.441305   0.227125
Ilker  50.000000  50.000000  -0.284926
Ceren  -0.638869   0.953292  -0.433535
Irem    0.266754   0.238779  -0.069103

In [68]:
new_indices = ["1-)","2-)","3-)","4-)"]

In [69]:
new_df["NewIndex"] = new_indices

In [70]:
new_df

          Salary        Age  Seniority NewIndex
Atıl    0.154754  -0.441305   0.227125      1-)
Ilker  50.000000  50.000000  -0.284926      2-)
Ceren  -0.638869   0.953292  -0.433535      3-)
Irem    0.266754   0.238779  -0.069103      4-)

In [72]:
new_df.set_index("NewIndex", inplace=True)

In [73]:
new_df

             Salary        Age  Seniority
NewIndex
1-)        0.154754  -0.441305   0.227125
2-)       50.000000  50.000000  -0.284926
3-)       -0.638869   0.953292  -0.433535
4-)        0.266754   0.238779  -0.069103

In [75]:
new_df.loc["1-)"]

Salary       0.154754
Age         -0.441305
Seniority    0.227125
Name: 1-), dtype: float64

In [76]:
# multi index

In [77]:
first_index = ["Simpson","Simpson","Simpson","South Park","South Park","South Park"]

In [78]:
inner_index = ["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [79]:
zipped_index = list(zip(first_index, inner_index))

In [80]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [81]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [82]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [83]:
sample_values = np.ones((6, 2))

In [84]:
sample_values

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [85]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Age", "Salary"])

In [86]:
big_df

                    Age  Salary
Simpson    Homer    1.0     1.0
           Bart     1.0     1.0
           Marge    1.0     1.0
South Park Cartman  1.0     1.0
           Kenny    1.0     1.0
           Kyle     1.0     1.0

In [89]:
big_df.loc["Simpson"].loc["Homer"]

Age       1.0
Salary    1.0
Name: Homer, dtype: float64